spring:
  application:
    name: integratehub-backend

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.mohsin.integratehub: DEBUG

integrations:
  weather:
    base-url: https://api.example-weather.com
    api-key: :)


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
