spring:
  application:
    name: integratehub-backend
  cache:
    type: simple
    cache-names:
      - weatherByCity
      - githubUserStats
      - currencyRates
      - stockQuotes
      - newsSearch

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.mohsin.integratehub: DEBUG

integrations:
  weather:
    base-url: https://api.open-meteo.com/v1/forecast
  github:
    base-url: https://api.github.com
  currency:
    base-url: http://api.exchangeratesapi.io/v1
    api-key: "81f7ee73b188517a571167be573eb2cf"
    snapshot:
      base: USD
      target: PKR
  stocks:
    base-url: https://www.alphavantage.co
    api-key: Y1G2CB73Q6KQYBMI
    snapshot:
      symbol: AAPL
  news:
    base-url: https://api.example-news.com
    api-key: :)
    snapshot:
      query: technology

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
