spring:
  application:
    name: integratehub-backend
  cache:
    type: simple
    cache-names:
      - weatherByCity
      - githubUserStats
      - currencyRates
      - stockQuotes


  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    com.mohsin.integratehub: DEBUG

integrations:
  weather:
    base-url: https://api.example-weather.com
    api-key: :)
  github:
    base-url: https://api.github.com
  currency:
    base-url: https://api.example-currency.com
    api-key: YOUR_CURRENCY_API_KEY_HERE
    snapshot:
      base: USD
      target: PKR

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
